version: '3.8'

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: bill-vending-service
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
        - custom_network
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bill_vending
    networks:
        - custom_network
    volumes:
      - db_data:/var/lib/postgresql/data
  pg-admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Admin@123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    networks:
        - custom_network
    depends_on:
      - db
    volumes:
        - pgadmin_data:/var/lib/pgadmin
        - ./pgadmin:/var/lib/pgadmin/storage
        - ./pgadmin/servers.json:/pgadmin4/servers.json:ro

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
        - custom_network
    volumes:
      - redis_data:/data

networks:
   custom_network:
     driver: bridge
volumes:
  redis_data:
  db_data:
  pgadmin_data:
